---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: grace1
  criSocket: unix:///run/containerd/containerd.sock
  taints: []
localAPIEndpoint:
  advertiseAddress: 147.102.4.89  # "public" IP of the node; default: GW
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.196.0.0/12  # default: 10.96/12
  podSubnet: 10.242.0.0/16  # same as in kube-flannel.yaml
kubernetesVersion: v1.30.2
apiServer:
  timeoutForControlPlane: 4m0s
controllerManager: {}
scheduler: {}
dns: {}
certificatesDir: /etc/kubernetes/pki
imageRepository: registry.k8s.io
clusterName: kubernetes
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
